/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.TempHousingRole;

import Business.EcoSystem;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.PermHousingRequest;
import Business.WorkQueue.TempHousingRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dhaan
 */
public class ProcessTempWorkRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    LabTestWorkRequest labrequest;
    EcoSystem System;
    TempHousingRequest tempHousingRequest;
    
    
    public ProcessTempWorkRequestJPanel(JPanel userProcessContainer, TempHousingRequest tempHousingRequest) {
        
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.tempHousingRequest = tempHousingRequest;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReject = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        btnAccept = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        resultJTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReject.setBackground(new java.awt.Color(204, 204, 204));
        btnReject.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        btnReject.setForeground(new java.awt.Color(0, 0, 0));
        btnReject.setText("Reject");
        btnReject.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });
        add(btnReject, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 120, 30));

        backJButton.setBackground(new java.awt.Color(204, 204, 204));
        backJButton.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        backJButton.setForeground(new java.awt.Color(0, 0, 0));
        backJButton.setText("Back");
        backJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 80, 20));

        btnAccept.setBackground(new java.awt.Color(204, 204, 204));
        btnAccept.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        btnAccept.setForeground(new java.awt.Color(0, 0, 0));
        btnAccept.setText("Accept");
        btnAccept.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 120, 30));

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Result");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 40, 20));
        jPanel1.add(resultJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 169, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        
        TempHousingWorkAreaJPanel dwjp = (TempHousingWorkAreaJPanel) component;
        dwjp.populateTempTable();
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed

        tempHousingRequest.setComment(resultJTextField.getText());

        tempHousingRequest.setStatus("Accepted");
        JOptionPane.showMessageDialog(null, "House Assigned to student: " + tempHousingRequest.getSender(), "Information", JOptionPane.INFORMATION_MESSAGE);
        btnAccept.setEnabled(false);
        btnReject.setEnabled(false);
        resultJTextField.setText("");
        tempHousingRequest.setMessage(resultJTextField.getText());


    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        tempHousingRequest.setComment(resultJTextField.getText());

        tempHousingRequest.setStatus("Rejected");
        JOptionPane.showMessageDialog(null, "House assignment rejected for" + tempHousingRequest.getSender(), "Information", JOptionPane.INFORMATION_MESSAGE);
        btnReject.setEnabled(false);
        btnAccept.setEnabled(false);
        tempHousingRequest.setMessage(resultJTextField.getText());

    }//GEN-LAST:event_btnRejectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField resultJTextField;
    // End of variables declaration//GEN-END:variables
}
