/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StudentRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.PermHousingOrganization;
import Business.Organization.StudentOrganization;
import Business.Organization.PartTimeOrganization;
import Business.UserAccount.UserAccount;
import Business.Student.StudentDirectory;
import Business.WorkQueue.PartTimeRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author dhaan
 */
public class RequestPartTimeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestPartTimeJPanel
     */
    private JPanel userProcessContainer;
    private StudentOrganization organization;
    private UserAccount userAccount;
    private EcoSystem system;
    private StudentDirectory vd;
    private Enterprise enterprise;
   

    RequestPartTimeJPanel(JPanel userProcessContainer, UserAccount userAccount, StudentDirectory vd, EcoSystem system) {
        initComponents();
        
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.system = system;
        this.vd = vd;
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        fundingAssistanceComboBox = new javax.swing.JComboBox<>();
        campusComboBox = new javax.swing.JComboBox<>();
        coursesComboBox = new javax.swing.JComboBox<>();
        educationComboBox = new javax.swing.JComboBox<>();
        txtSubmit = new javax.swing.JButton();
        txtAdditionalSkills = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Niramit", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Apply for Part-time Job");
        jLabel1.setFocusable(false);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 22, -1, -1));

        fundingAssistanceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        add(fundingAssistanceComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 200, 171, -1));

        campusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Online", "Boston", "New Jersey", "Phoenix" }));
        add(campusComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 138, 171, -1));

        coursesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Graduate Office Front Desk ", "Receation Club Assistant", "Library Assistant", "Library Help", "Library Tech Support", " " }));
        coursesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursesComboBoxActionPerformed(evt);
            }
        });
        add(coursesComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 108, -1, -1));

        educationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High School", "High School Diploma", "Bachelors", "Masters" }));
        add(educationComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 170, 171, -1));

        txtSubmit.setBackground(new java.awt.Color(204, 204, 204));
        txtSubmit.setText("Submit");
        txtSubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubmitActionPerformed(evt);
            }
        });
        add(txtSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 289, 171, 39));
        add(txtAdditionalSkills, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 236, 171, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Area of Interest");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 113, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Campus");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 143, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Highest Qualification");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 175, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Funding Required?");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 205, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Additional Information");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 236, -1, -1));

        backJButton.setBackground(new java.awt.Color(204, 204, 204));
        backJButton.setText("<<Back");
        backJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 358, 68, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void coursesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coursesComboBoxActionPerformed

    private void txtSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubmitActionPerformed
        // TODO add your handling code here:

        PartTimeRequest request = new PartTimeRequest();
        
        
        request.setMessage(txtAdditionalSkills.getText());
        request.setSender(userAccount);
        request.setStatus("Sent");
        
        
        request.setAreaOfInterest((String) coursesComboBox.getSelectedItem());
        request.setHighestQualification((String) educationComboBox.getSelectedItem());
        request.setCampus((String) campusComboBox.getSelectedItem());
        request.setFundingRequired((String) fundingAssistanceComboBox.getSelectedItem());
        request.setAdditionalComments(txtAdditionalSkills.getText());


        Organization org = null;
        System.out.println("Collected Variables");
        System.out.println(coursesComboBox.getSelectedItem());
        
        

        for (Network network : system.getNetworkList()) {
            //Step 2.a: check against each enterprise
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                System.out.println(enterprise);

//                    userAccount = enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                //Step 3:check against each organization for each enterprise
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    System.out.println(organization);

                    if (organization instanceof PartTimeOrganization) {
                        org = organization;

                        System.out.println(org);
                        break;
                        
                        
                    }

                }
            }
        }
        
        
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request);
            System.out.println("Added VocationalRequest to Org");
            userAccount.getWorkQueue().getWorkRequestList().add(request);
            System.out.println("Added VocationalRequest to UserAccount");

            JOptionPane.showMessageDialog(null, "Request Submitted Successfully", "Information", JOptionPane.INFORMATION_MESSAGE);

        }


    }//GEN-LAST:event_txtSubmitActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        
        
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        
        
        StudentWorkAreaJPanel dwjp = (StudentWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox<String> campusComboBox;
    private javax.swing.JComboBox<String> coursesComboBox;
    private javax.swing.JComboBox<String> educationComboBox;
    private javax.swing.JComboBox<String> fundingAssistanceComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtAdditionalSkills;
    private javax.swing.JButton txtSubmit;
    // End of variables declaration//GEN-END:variables
}
