/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StudentRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Organization.PermHousingOrganization;
import Business.Organization.StudentOrganization;
import Business.UserAccount.UserAccount;
import Business.Student.StudentDirectory;
import Business.WorkQueue.GradSchoolRequest;
import Business.WorkQueue.JobWorkRequest;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.MentalHealthCareRequest;
import Business.WorkQueue.PermHousingRequest;
import Business.WorkQueue.PhysicalHealthCareRequest;
import Business.WorkQueue.TempHousingRequest;
import Business.WorkQueue.PartTimeRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import static java.time.Clock.system;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.DoctorRole.RequestLabTestJPanel;

/**
 *
 * @author dhaan
 */
public class StudentWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private StudentOrganization organization;
    private Enterprise enterprise;
     private EcoSystem system;
    private StudentDirectory vd;
    private UserAccount userAccount;
   
    
//    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    /**
     * Creates new form StudentWorkAreaJPanel
     */
    public StudentWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, StudentOrganization organization, Enterprise enterprise, StudentDirectory vd) {
        initComponents();
        
        

        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        
        
        populateRequestTable();

    }

    public StudentWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, StudentDirectory vd, EcoSystem system) {

        initComponents();
        
        
        this.userProcessContainer = userProcessContainer;
        this.vd = vd;
        this.userAccount = userAccount;
        this.system = system;

//        system = dB4OUtil.retrieveSystem();
        populateRequestTable();
//        populateTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshTestJButton = new javax.swing.JButton();
        permhousingrequestjButton = new javax.swing.JButton();
        VocationalRequestJButton = new javax.swing.JButton();
        GradRequestJButton = new javax.swing.JButton();
        PhysicalHealthCareRequestJButton = new javax.swing.JButton();
        MentalHealthCareJButton = new javax.swing.JButton();
        txtWelcome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        permhousingrequestjButton1 = new javax.swing.JButton();
        txtTotalRequests1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        eduRequestsTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        refreshTestJButton.setBackground(new java.awt.Color(204, 204, 204));
        refreshTestJButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        refreshTestJButton.setForeground(new java.awt.Color(0, 0, 0));
        refreshTestJButton.setText("Refresh");
        refreshTestJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        refreshTestJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });
        add(refreshTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 100, 40));

        permhousingrequestjButton.setBackground(new java.awt.Color(204, 204, 204));
        permhousingrequestjButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        permhousingrequestjButton.setForeground(new java.awt.Color(0, 0, 0));
        permhousingrequestjButton.setText("Perm Housing Request");
        permhousingrequestjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        permhousingrequestjButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        permhousingrequestjButton.setMaximumSize(new java.awt.Dimension(142, 25));
        permhousingrequestjButton.setMinimumSize(new java.awt.Dimension(142, 25));
        permhousingrequestjButton.setPreferredSize(new java.awt.Dimension(152, 32));
        permhousingrequestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permhousingrequestjButtonActionPerformed(evt);
            }
        });
        add(permhousingrequestjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 270, 30));

        VocationalRequestJButton.setBackground(new java.awt.Color(204, 204, 204));
        VocationalRequestJButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        VocationalRequestJButton.setForeground(new java.awt.Color(0, 0, 0));
        VocationalRequestJButton.setText("Part-Time Job");
        VocationalRequestJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        VocationalRequestJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        VocationalRequestJButton.setMaximumSize(new java.awt.Dimension(142, 25));
        VocationalRequestJButton.setMinimumSize(new java.awt.Dimension(142, 25));
        VocationalRequestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VocationalRequestJButtonActionPerformed(evt);
            }
        });
        add(VocationalRequestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 270, 30));

        GradRequestJButton.setBackground(new java.awt.Color(204, 204, 204));
        GradRequestJButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        GradRequestJButton.setForeground(new java.awt.Color(0, 0, 0));
        GradRequestJButton.setText("Apply for Grad School");
        GradRequestJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GradRequestJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        GradRequestJButton.setPreferredSize(new java.awt.Dimension(152, 32));
        GradRequestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradRequestJButtonActionPerformed(evt);
            }
        });
        add(GradRequestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 270, 30));

        PhysicalHealthCareRequestJButton.setBackground(new java.awt.Color(204, 204, 204));
        PhysicalHealthCareRequestJButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        PhysicalHealthCareRequestJButton.setForeground(new java.awt.Color(0, 0, 0));
        PhysicalHealthCareRequestJButton.setText("Physical Healthcare Request");
        PhysicalHealthCareRequestJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PhysicalHealthCareRequestJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PhysicalHealthCareRequestJButton.setMaximumSize(new java.awt.Dimension(142, 25));
        PhysicalHealthCareRequestJButton.setMinimumSize(new java.awt.Dimension(142, 25));
        PhysicalHealthCareRequestJButton.setPreferredSize(new java.awt.Dimension(152, 32));
        PhysicalHealthCareRequestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhysicalHealthCareRequestJButtonActionPerformed(evt);
            }
        });
        add(PhysicalHealthCareRequestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 280, 30));

        MentalHealthCareJButton.setBackground(new java.awt.Color(204, 204, 204));
        MentalHealthCareJButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        MentalHealthCareJButton.setForeground(new java.awt.Color(0, 0, 0));
        MentalHealthCareJButton.setText("Mental Healthcare Request");
        MentalHealthCareJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MentalHealthCareJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MentalHealthCareJButton.setMaximumSize(new java.awt.Dimension(142, 25));
        MentalHealthCareJButton.setMinimumSize(new java.awt.Dimension(142, 25));
        MentalHealthCareJButton.setPreferredSize(new java.awt.Dimension(152, 32));
        MentalHealthCareJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MentalHealthCareJButtonActionPerformed(evt);
            }
        });
        add(MentalHealthCareJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 280, 30));

        txtWelcome.setBackground(new java.awt.Color(42, 42, 42));
        txtWelcome.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        txtWelcome.setForeground(new java.awt.Color(255, 255, 255));
        add(txtWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 480, 50));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Get Medical Help");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 370, -1));

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apply for Housing");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 370, -1));

        permhousingrequestjButton1.setBackground(new java.awt.Color(204, 204, 204));
        permhousingrequestjButton1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        permhousingrequestjButton1.setForeground(new java.awt.Color(0, 0, 0));
        permhousingrequestjButton1.setText("Temp Housing Request");
        permhousingrequestjButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        permhousingrequestjButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        permhousingrequestjButton1.setMaximumSize(new java.awt.Dimension(142, 25));
        permhousingrequestjButton1.setMinimumSize(new java.awt.Dimension(142, 25));
        permhousingrequestjButton1.setPreferredSize(new java.awt.Dimension(152, 32));
        permhousingrequestjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permhousingrequestjButton1ActionPerformed(evt);
            }
        });
        add(permhousingrequestjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 270, -1));

        txtTotalRequests1.setBackground(new java.awt.Color(51, 51, 51));
        txtTotalRequests1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtTotalRequests1.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalRequests1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTotalRequests1.setFocusable(false);
        txtTotalRequests1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(txtTotalRequests1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 110, 70));

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apply for Education");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 370, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 492, 20));

        eduRequestsTable.setBackground(new java.awt.Color(204, 204, 204));
        eduRequestsTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eduRequestsTable.setForeground(new java.awt.Color(0, 0, 0));
        eduRequestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "RequestType", "AssignedTo", "Status", "RequestedOn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(eduRequestsTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 540, 210));

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("My Requests:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 300, -1));

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total Requests Raised:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 350, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateRequestTable();


    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void permhousingrequestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permhousingrequestjButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestPermHousingJPanel", new RequestPermHousingJPanel(userProcessContainer, userAccount, vd, system));
        layout.next(userProcessContainer);

    }//GEN-LAST:event_permhousingrequestjButtonActionPerformed

    private void VocationalRequestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VocationalRequestJButtonActionPerformed
        // TODO add your handling code here:

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestVocTrainingJPanel", new RequestPartTimeJPanel(userProcessContainer, userAccount, vd, system));
        layout.next(userProcessContainer);

    }//GEN-LAST:event_VocationalRequestJButtonActionPerformed

    private void GradRequestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradRequestJButtonActionPerformed
        // TODO add your handling code here

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestGradJPanel", new RequestGradJPanel(userProcessContainer, userAccount, vd, system));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_GradRequestJButtonActionPerformed

    private void PhysicalHealthCareRequestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhysicalHealthCareRequestJButtonActionPerformed

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("Request_PHC_JPanel", new Request_PHC_JPanel(userProcessContainer, userAccount, vd, system));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_PhysicalHealthCareRequestJButtonActionPerformed

    private void MentalHealthCareJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MentalHealthCareJButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("Request_MHC_JPanel", new Request_MHC_JPanel(userProcessContainer, userAccount, vd, system));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_MentalHealthCareJButtonActionPerformed

    private void permhousingrequestjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permhousingrequestjButton1ActionPerformed
        // TODO add your handling code here:
         CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestTempHousingJPanel", new RequestTempHousingJPanel(userProcessContainer, userAccount, vd, system));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_permhousingrequestjButton1ActionPerformed

    public void populateRequestTable() {
        
        txtWelcome.setText("Welcome back, " + userAccount.getUsername());


        DefaultTableModel eduModel = (DefaultTableModel) eduRequestsTable.getModel();
         eduModel.setRowCount(0);
        int totalRequests = 0;
        int acceptedRequests = 0;
        int rejectedRequests = 0;



        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
            totalRequests = totalRequests + 1;

            if (request instanceof PartTimeRequest) {
                Object[] row = new Object[5];
                row[0] = "VocationalTraining";
                row[1] = request.getReceiver();
                row[2] = request.getStatus();

                row[3] = request.getRequestDate();

                eduModel.addRow(row);
            }

            if (request instanceof GradSchoolRequest) {
                Object[] row = new Object[5];
                row[0] = "Grad School";
                row[1] = request.getReceiver();
                row[2] = request.getStatus();

                row[3] = request.getRequestDate();
                eduModel.addRow(row);
            }

            if (request instanceof PhysicalHealthCareRequest) {
                Object[] row = new Object[5];
                row[0] = "Physical Healthcare";
                row[1] = request.getReceiver();
                row[2] = request.getStatus();
                row[3] = request.getRequestDate();
                eduModel.addRow(row);
            }

            if (request instanceof MentalHealthCareRequest) {
                Object[] row = new Object[5];
                row[0] = "Mental Healthcare";
                row[1] = request.getReceiver();
                row[2] = request.getStatus();
                row[3] = request.getRequestDate();
                row[4]=request.getResolveDate();
                eduModel.addRow(row);
            }

            if (request instanceof TempHousingRequest) {
                Object[] row = new Object[5];
                row[0] = "Temp Housing";
                row[1] = request.getReceiver();
                row[2] = request.getStatus();
                row[3] = request.getRequestDate();
                row[4]=request.getResolveDate();
                eduModel.addRow(row);
            }

            if (request instanceof PermHousingRequest) {
                Object[] row = new Object[5];
                row[0] = "Permanent Housing";
                row[1] = request.getReceiver();
                row[2] = request.getStatus();
                row[3] = request.getRequestDate();
                row[4]=request.getResolveDate();
                eduModel.addRow(row);
            }

            
            
            if (request instanceof JobWorkRequest) {
                Object[] row = new Object[5];
                row[0] = "Employment Request";
                row[1] = request.getReceiver();
                row[2] = request.getStatus();
                row[3] = request.getRequestDate();
                row[4]=request.getResolveDate();
                eduModel.addRow(row);
            }

        }

        txtTotalRequests1.setText(Integer.toString(totalRequests));
       

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GradRequestJButton;
    private javax.swing.JButton MentalHealthCareJButton;
    private javax.swing.JButton PhysicalHealthCareRequestJButton;
    private javax.swing.JButton VocationalRequestJButton;
    private javax.swing.JTable eduRequestsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton permhousingrequestjButton;
    private javax.swing.JButton permhousingrequestjButton1;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JLabel txtTotalRequests1;
    private javax.swing.JLabel txtWelcome;
    // End of variables declaration//GEN-END:variables
}
