/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PermHousing;


import java.awt.CardLayout;
import java.awt.Component;
import userinterface.LabAssistantRole.*;
import Business.WorkQueue.LabTestWorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.EcoSystem;
import Business.WorkQueue.PermHousingRequest;



/**
 *
 * @author dhaan
 */
public class ProcessPermWorkRequestJPanel extends javax.swing.JPanel {

    
    LabTestWorkRequest labrequest;
    JPanel userProcessContainer;
    EcoSystem System;
    PermHousingRequest permHousingRequest;
    
    
    
    //int method = 0;
    /**
     * Creates new form ProcessWorkRequestJPanel
     */
     public ProcessPermWorkRequestJPanel(JPanel userProcessContainer, PermHousingRequest permHousingRequest,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.permHousingRequest = permHousingRequest;
        this.System = system;
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        resultJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        btnAccept = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Result");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));
        add(resultJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 169, -1));

        backJButton.setBackground(new java.awt.Color(204, 204, 204));
        backJButton.setText("Back");
        backJButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 50, -1));

        btnAccept.setBackground(new java.awt.Color(204, 204, 204));
        btnAccept.setText("Accept");
        btnAccept.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 130, 40));

        btnReject.setBackground(new java.awt.Color(204, 204, 204));
        btnReject.setText("Reject");
        btnReject.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });
        add(btnReject, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 130, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        
        PermHousingWorkAreaJPanel dwjp = (PermHousingWorkAreaJPanel) component;
       
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed
//added newly
    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed

        permHousingRequest.setAvailibility(1);
        permHousingRequest.setComment(resultJTextField.getText());

        permHousingRequest.setStatus("Accepted");
        JOptionPane.showMessageDialog(null, "House Assigned to student: " + permHousingRequest.getSender(), "Information", JOptionPane.INFORMATION_MESSAGE);
        btnAccept.setEnabled(false);
        btnReject.setEnabled(false);
        resultJTextField.setText("");
        


    }//GEN-LAST:event_btnAcceptActionPerformed
//added newly
    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        permHousingRequest.setAvailibility(0);
        permHousingRequest.setComment(resultJTextField.getText());

        permHousingRequest.setStatus("Rejected");
        JOptionPane.showMessageDialog(null, "House assignment rejected for" + permHousingRequest.getSender(), "Information", JOptionPane.INFORMATION_MESSAGE);
        btnReject.setEnabled(false);
        btnAccept.setEnabled(false);

    }//GEN-LAST:event_btnRejectActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField resultJTextField;
    // End of variables declaration//GEN-END:variables
}
